<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MyGenie" failures="5" tests="70" name="Test" time="35.645" errors="0" timestamp="2025-02-05T21:13:20 CST">
  <testcase classname="testCase.SwaggerAPI" name="GetAllUsersTest" time="2.186"/>
  <testcase classname="testCase.SwaggerAPI" name="GetAllUsersTest" time="0.415"/>
  <testcase classname="testCase.SwaggerAPI" name="GetAllUsersTest" time="0.413"/>
  <testcase classname="testCase.SwaggerAPI" name="GetAllUsersTest" time="0.623"/>
  <testcase classname="testCase.SwaggerAPI" name="GetAllUsersTest" time="0.422"/>
  <testcase classname="testCase.SwaggerAPI" name="GetAllUsersTest" time="2.654"/>
  <testcase classname="testCase.SwaggerAPI" name="GetAllUsersTest" time="0.006">
    <skipped/>
  </testcase> <!-- GetAllUsersTest -->
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.798"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.421"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.436"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.431"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.296"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.542"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.545"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.444"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.427"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.444"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.433"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.424"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.445"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.436"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.414"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.424"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="1.232"/>
  <testcase classname="testCase.SwaggerAPI" name="CreateUser" time="0.454"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByIdTest" time="0.435"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByIdTest" time="0.518"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByIdTest" time="0.422"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByIdTest" time="0.448">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;404&amp;gt; but was &amp;lt;400&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <404> but was <400>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at testCase.SwaggerAPI.GetUserByIdTest(SwaggerAPI.java:104)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- GetUserByIdTest -->
  <testcase classname="testCase.SwaggerAPI" name="GetUserByIdTest" time="0.272"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByIdTest" time="0.731"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByIdTest" time="0.419"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByFNameTest" time="0.404"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByFNameTest" time="0.414"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByFNameTest" time="0.394"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByFNameTest" time="0.417"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByFNameTest" time="0.277"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByFNameTest" time="0.419"/>
  <testcase classname="testCase.SwaggerAPI" name="GetUserByFNameTest" time="0.417"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.455">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Response body doesn&amp;apos;t match expectation.
Expected: The content to match the given JSON schema.
error: object has missing required properties ([&amp;quot;creation_time&amp;quot;,&amp;quot;last_mod_time&amp;quot;,&amp;quot;userAddress&amp;quot;,&amp;quot;user_contact_number&amp;quot;,&amp;quot;user_email_id&amp;quot;,&amp;quot;user_first_name&amp;quot;,&amp;quot;user_id&amp;quot;,&amp;quot;user_last_name&amp;quot;])
    level: &amp;quot;error&amp;quot;
    schema: {&amp;quot;loadingURI&amp;quot;:&amp;quot;file:/C:/Users/madhu/OneDrive/Desktop/SDET/RestAssured_Testng/target/classes/schema1.json#&amp;quot;,&amp;quot;pointer&amp;quot;:&amp;quot;&amp;quot;}
    instance: {&amp;quot;pointer&amp;quot;:&amp;quot;&amp;quot;}
    domain: &amp;quot;validation&amp;quot;
    keyword: &amp;quot;required&amp;quot;
    required: [&amp;quot;creation_time&amp;quot;,&amp;quot;last_mod_time&amp;quot;,&amp;quot;userAddress&amp;quot;,&amp;quot;user_contact_number&amp;quot;,&amp;quot;user_email_id&amp;quot;,&amp;quot;user_first_name&amp;quot;,&amp;quot;user_id&amp;quot;,&amp;quot;user_last_name&amp;quot;]
    missing: [&amp;quot;creation_time&amp;quot;,&amp;quot;last_mod_time&amp;quot;,&amp;quot;userAddress&amp;quot;,&amp;quot;user_contact_number&amp;quot;,&amp;quot;user_email_id&amp;quot;,&amp;quot;user_first_name&amp;quot;,&amp;quot;user_id&amp;quot;,&amp;quot;user_last_name&amp;quot;]

  Actual: {&amp;quot;status&amp;quot;:&amp;quot;400 BAD_REQUEST&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Contact number is already in use by another user&amp;quot;}
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: The content to match the given JSON schema.
error: object has missing required properties (["creation_time","last_mod_time","userAddress","user_contact_number","user_email_id","user_first_name","user_id","user_last_name"])
    level: "error"
    schema: {"loadingURI":"file:/C:/Users/madhu/OneDrive/Desktop/SDET/RestAssured_Testng/target/classes/schema1.json#","pointer":""}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "required"
    required: ["creation_time","last_mod_time","userAddress","user_contact_number","user_email_id","user_first_name","user_id","user_last_name"]
    missing: ["creation_time","last_mod_time","userAddress","user_contact_number","user_email_id","user_first_name","user_id","user_last_name"]

  Actual: {"status":"400 BAD_REQUEST","message":"Contact number is already in use by another user"}

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:107)
at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:238)
at testCase.SwaggerAPI.UpdateUser(SwaggerAPI.java:292)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- UpdateUser -->
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.596"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.417"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.418"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.406"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.408"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.42"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.4"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.417"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.41"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.405"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.405"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.281"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.418"/>
  <testcase classname="testCase.SwaggerAPI" name="UpdateUser" time="0.412"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByIdTest" time="0.004"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByIdTest" time="0.397"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByIdTest" time="0.488"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByIdTest" time="0.405"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByIdTest" time="0.269"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByIdTest" time="0.411"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByIdTest" time="0.413"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByIdTest" time="0.427"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByFNameTest" time="0.005"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByFNameTest" time="0.401"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByFNameTest" time="0.435"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByFNameTest" time="0.405"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByFNameTest" time="0.299"/>
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByFNameTest" time="0.403">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;400&amp;gt; but was &amp;lt;405&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <400> but was <405>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at testCase.SwaggerAPI.DeleteUserByFNameTest(SwaggerAPI.java:375)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DeleteUserByFNameTest -->
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByFNameTest" time="0.392">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;404&amp;gt; but was &amp;lt;405&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <404> but was <405>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at testCase.SwaggerAPI.DeleteUserByFNameTest(SwaggerAPI.java:385)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DeleteUserByFNameTest -->
  <testcase classname="testCase.SwaggerAPI" name="DeleteUserByFNameTest" time="0.409">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;405&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <405>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at testCase.SwaggerAPI.DeleteUserByFNameTest(SwaggerAPI.java:355)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DeleteUserByFNameTest -->
</testsuite> <!-- Test -->
